# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [5]:
print(np.__version__)
print(np.show_config())

1.19.0
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10

In [8]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [12]:
arr = np.array([1,2,3,4,5,6,7])
np.size(arr)
print("%d Bytes" % (arr.size * arr.itemsize))

28 Bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [6]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [14]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [16]:
arr = np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last)

In [28]:
arr = np.arange(10,20)
print(arr)
arr = arr[::-1]
print(arr)

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [32]:
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [33]:
arr = np.array([1,2,0,0,4,0])
result = np.nonzero(arr)
print(result)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [17]:
arr = np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [35]:
arr = np.random.random((3,3,3))
print("arr \n", arr)

arr 
 [[[0.86802543 0.99845998 0.81394011]
  [0.14609417 0.91013668 0.13687813]
  [0.85212832 0.75761954 0.56316711]]

 [[0.39569077 0.49555394 0.44939597]
  [0.7231844  0.32235793 0.60986589]
  [0.99317192 0.78557317 0.57182198]]

 [[0.49408251 0.39542347 0.23184135]
  [0.62056534 0.91582285 0.22025325]
  [0.97671431 0.46111843 0.10747123]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [40]:
arr = np.random.random((10,10))
print(arr)
print(np.min(arr))

[[0.32101574 0.43733864 0.3520021  0.59750053 0.28467858 0.84317779
  0.68056234 0.3628329  0.41168193 0.83271655]
 [0.77733174 0.52071834 0.24469275 0.37450806 0.80346205 0.47191166
  0.92929745 0.91089337 0.55924738 0.37097278]
 [0.01920834 0.33063263 0.96874537 0.4881529  0.27692451 0.45402008
  0.3923428  0.90685919 0.25316619 0.47501366]
 [0.65087415 0.35400711 0.04894093 0.74928693 0.4342096  0.25596424
  0.27924738 0.60530905 0.41174078 0.90440232]
 [0.62313476 0.73642806 0.18503962 0.58892673 0.57622583 0.14650758
  0.73043602 0.31009678 0.13942942 0.62627251]
 [0.00913218 0.33357421 0.56128067 0.8317885  0.44347084 0.35045153
  0.47526188 0.01217602 0.93106164 0.15059829]
 [0.46257472 0.96269019 0.04862317 0.04450411 0.78892722 0.23751735
  0.91670165 0.00181405 0.06248457 0.58955577]
 [0.24138235 0.5852633  0.34308327 0.66271306 0.06671709 0.85765354
  0.65823609 0.27599299 0.85913815 0.44784619]
 [0.1920773  0.49922334 0.53522783 0.62972955 0.08888857 0.08844234
  0.05598568

#### 14. Create a random vector of size 30 and find the mean value

In [42]:
arr = np.arange(30)
print(np.mean(arr))

14.5


#### 15. Create a 2d array with 1 on the border and 0 inside

In [48]:
arr = np.ones((5,5),dtype='int')
arr[1:-1,1:-1] = 0
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [52]:
arr = np.ones((5,5),dtype='int')
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [54]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [70]:
arr = np.diag([1,2,3,4],k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [79]:
arr = np.zeros((8,8), dtype = 'int')
arr[0::2,1::2] = 1
arr[1::2,0::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [99]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)
